acquia/drupal-recommended-project

composer.json
Per discussion in ORCA Slack, this will unblock some other things. This dependency was added last year when only a beta was available, I think that's the only reason it was constrained to beta at the time.
=> Bump mysql56 to stable

composer.json
Also force update of Acquia CMS. Older versions are broken due to patch failures and unconstrained dependencies, and can get installed unintentionally due to missing PHP extensions.
=> Composer should exit on patch failure

.github/workflows/orca.yml, README.md, composer.json, composer.lock
This has several benefits:
- Provides known-good package versions, avoiding sudden breakage due to upstream changes
- Prevents issues like https://github.com/acquia/drupal-recommended-project/pull/33 where older or broken dependencies are pulled due to missing platform dependencies
- Much faster installs, since Composer doesn't have to recalculate the dependency tree each time (~5s instead of 20s on my machine)
We didn't do this before because it would either give people out-of-date packages or require us to constantly update them. But with Violinist this can be handled automatically.
To do:
=> Provide composer.lock

.gitignore
Drupal core doesn't commit settings.php because it's automatically created at install time. But this isn't possible on Acquia Cloud's read-only fs.
This explains the confusion in https://github.com/acquia/drupal-recommended-project/pull/63 .
=> Explain gitignore mod

composer.json, composer.lock
Allow Drush 11. Drush 10 is unsupported.
This PR still allows Drush 10 since many other packages (E.g. ACMS) still _require_ Drush 10 and would therefor conflict with this package.
=> Allow Drush 11

README.md
Fix #161 
I removed the lock file from the drupal10 branch so that dependencies stay up to date without having to mess with our automation.
I also had to remove several packages with conflicts with D10 just to get it to install, so it may not be very useful as an integration environment.
@mikemadison13 @anavarre take a look since you requested this
=> DX-5132: D10 testing branch

.gitignore
Headless Next.js starter kit oauth keys need to support Acquia Cloud
**Motivation**
./oauth_keys is the location where there keys are stored which is not covered by .gitignore from the drupal-recommended-project. This could lead to customers committing oauth keys to their git repositories.
Fixes #ACMS-1320
Add ./oauth_keys in .gitignore
NA
- Create project with this codebase
- init git repo
- install headless starterkit `./vendor/bin/acms acms:install acquia_cms_headless`
- now with `git status` newly created ./oauth_keys directory should not be listed.
=> ACMS-1320: Headless Next.js starter kit oauth keys need to support Acquia Cloud

.github/workflows/orca.yml
**Motivation**
Enables jobs to test D10 readiness . [ORCA-411](https://backlog.acquia.com/browse/ORCA-411)
Enabled the following jobs
1. ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV
2. INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV
3. ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER
4. INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER
=> Enable d10-jobs

.github/workflows/orca.yml
**Motivation**
This to upgrade node version  to 16.x as 12.x is deprecated and throwing multiple warnings.
=> Upgrade node version to 16.x

.github/workflows/orca.yml, composer.json
Latest version of Acquia Search requires acquia/http-hmac-php >=5 , we are updating this to version 6.0.0 here to have parity with main branch . Details in https://backlog.acquia.com/browse/ORCA-475.
=> ORCA-475: Removing http-hmac-php and Integrate with ORCA

.github/workflows/orca.yml, composer.json, composer.lock
**Motivation**
Make a new release for 1.x branch of DRP.
- Restrict Drupal Core to 9.x.
- Updated ORCA CI to tests on only 9.x release.
N/A
- ORCA CI tests should pass.
- Manual Testing
=> ACMS-1629: Restrict Drupal Core to 9.x release for 1.x branch of DRP.

.github/dependabot.yml, .github/workflows/orca.yml, README.md, composer.json, composer.lock
**Motivation**
Fixes: [ACMS-1629](https://backlog.acquia.com/browse/ACMS-1629).
- Removed upgrade_status module.
- Minimum required `PHP` is PHP 8.1.
- Minimum required `drupal/core-composer-scaffold` & `drupal/core-recommended ` is 10.0.
- Drupal core upgraded to 10.0.1.
- Dropped 10.x support for `drush/drush`.
- Dropped 1.x support for `oomphinc/composer-installers-extender`.
N/A.
- CI tests should pass.
- Manual Testing.
=>  Upgrade Drupal Core to 10.

README.md, composer.json, composer.lock
**Motivation**
Updated Readme.md and remove package acquia/http-hmac-php as per ORCA-475.
- The README.md file updated as per Drupal 10.
- The package `acquia/http-hmac-php` has been removed as per ORCA-475.
N/A.
- ORCA CI should pass.
=> ACMS-1629: Updated README.md file and remove acquia/http-hmac-php as per ORCA-475.

.github/release-drafter-1.x.yml, .github/workflows/release-drafter.yml
**Motivation**
Added github release drafter for 1.x & 2.x releases.
- Added a new release drafter for 1.x, restricting to release from 1.x branch.
- Default release drafter updated to restrict release from master branch.
- Workflow for default release drafter updated to use default release drafter config.
N/A.
- CI should pass.
- Automatic release should be created.
=> ACMS-1651: Add release drafter for 2.x & 1.x releases.

.github/workflows/release-drafter-1.x.yml
**Motivation**
Added github release drafter for 1.x release.
- Release drafter configuration renamed.
- Release drafter configuration update to use release drafter 1.x configuration.
N/A.
- CI should pass.
- Automatic release should be created
=> ACMS-1651: Add release drafter for 1.x releases.

.github/workflows/automerge.yml
**Motivation**
Fixes ACMS-1708
The `Auto Merge` workflow config was missing the config-name parameter, due to which looks like workflow creating the release from default config which uses the master branch and thus create release for 2.x branch.
N/A.
Merge PR for 1.x branch & see if it create a release on 1.x (and not on 2.x).
=> ACMS-1708: Fix the empty releases created by release-drafter.

.github/workflows/orca.yml
- The following jobs are added
- INTEGRATED_TEST_ON_LATEST_LTS
- The following jobs are removed since they are not representing Drupal 9 anymore.
- INTEGRATED_TEST_ON_PREVIOUS_MINOR
=> ORCA-524: Add php 8.2 tests for 1.x

.github/workflows/orca.yml
- The following jobs are added
- INTEGRATED_TEST_ON_PREVIOUS_MINOR
- ISOLATED_TEST_ON_CURRENT
=> ORCA-524: Add PHP 8.2 tests

composer.json, composer.lock
**Motivation**
Fixes #[ACMS-1934](https://backlog.acquia.com/browse/ACMS-1934)
Add drupal/config_sync_without_site_uuid project plugin.
NA
Follow from ticket.
=> ACMS-1934: Add drupal/config_sync_without_site_uuid project plugin.

.github/workflows/orca.yml
We are adding Drupal 9 tests for PHP 8.1 and PHP 8.0.
=> Add Drupal 9 tests

README.md, composer.json, composer.lock
**Motivation**
Includes the `acquia/drupal-recommended-settings` plugin to the project.
- Updated composer dependency to include `acquia/drupal-recommended-settings` plugin.
N/A
- Create the acquia/drupal-recommended-project and you should see the following files created by the plugin:
- salt.txt
- docroot/sites/default/settings.php
- docroot/sites/default/settings/local.settings.php
- docroot/sites/default/settings/default.local.settings.php
=> ACMS-1866: Include acquia/drupal-recommended-settings plugin.

.github/workflows/automerge.yml, .github/workflows/release-drafter.yml
**Motivation**
The Release Drafter is creating `2.2.0` and `3.0.0` release from `master` branch. Looks like release drafter is not working as expected on beta releases. 
Commenting the Release drafter code Until D11 stable release is made.
N/A
The release drafter shouldn't create any releases from `master` branch,
=> HOTFIX: Commenting Release drafter until D11 is released.

README.md
Removing the instructions for adding BLT from the README since BLT is incompatible with Drupal 11.
**Motivation**
Prevents confusion for folks reading the README for instructions for installing Drupal by removing installation instructions for BLT (which is no longer supported) 
No updates are required. Minimal impact on end users.
This could potentially be resolved through some additional testing updates added to BLT to detect the version, and that probably exists, but this seems like a small change that would prevent teams from investing time or resources. 
Check for BLT in the README.md code
=> Update README.md remove BLT

composer.json, composer.lock
**Motivation**
The Drupal 11 requires minimum PHP 8.3. So, updated dependencies.
Minimum PHP requirement updated to 8.3.
N/A
The CI should pass.
=> ACMS-000: Set minimum PHP requirement to 8.3

README.md
Label has been changed from "Acquia CMS" to "Acquia Drupal Starter Kit"
**Motivation**
ACMS-4201
=> Change Label to Acquia Drupal Starter Kit
