acquia/drupal-recommended-project

.travis.yml
packages_alter.yml

https://github.com/acquia/orca/pull/91

Improve ORCA patch

---

.travis.yml

https://github.com/acquia/orca/pull/115

Upgrade to ORCA 3

---

.gitignore

Fixes #12 
I'll cut a new release after this if everything looks good

DX-3087: Clean up gitignore file

---

composer.json

I'm not sure why we didn't include this in the first place, hopefully there's not a conflict with ORCA or something.

Include blt-phpcs

---

.travis.yml
README.md
composer.json

This reverts commit 08cb476148befc0a445ca611ca9bb1c90191283e.

Revert "Switch to Acquia CMS (#24)"

---

README.md
composer.json

Change the default profile from Lightning to Acquia CMS.

Change to Acquia CMS

---

.github/workflows/orca.yml

https://github.com/acquia/orca/pull/183

[orca] custom jobs never fail

---

composer.json
composer.lock

Regression caused by https://github.com/acquia/drupal-recommended-project/commit/769b1a62b1bf5b829142a122a361e0e28598e108

Fix broken tests

---

composer.json
composer.lock

https://github.com/hiqdev/asset-packagist/issues/146

Remove Asset Packagist

---

README.md
composer.json
composer.lock

- Removed [acquia/acquia_cms](https://github.com/acquia/acquia_cms) in favor of latest stable release of Acquia CMS Starter kit.
- Updated README.md file accordingly.

ACMS-000: Release Acquia CMS Starter kit & remove acquia/acquia_cms.

---

composer.json
composer.lock

Fixes the issue related to `acms:install` command

Fix the acms install command.

---

composer.json

Issue - https://github.com/acquia/drupal-recommended-project/issues/227

Disable timeout for acms:install script

---

.gitignore

**Motivation**
Fixes #ACMS-1377(https://backlog.acquia.com/browse/ACMS-1377)

ACMS-1377: Ensure the .gitignore file excludes .env* files.

---

.github/workflows/orca.yml

https://github.com/acquia/orca/pull/294

ORCA-452: Patch ORCA

---

composer.lock

Update Acquia CMS Starterkit.

---

README.md

**Motivation**
Fixes #ACMS-1726
Update readme with instructions to install ACMS out-of-the-box after creating project using Acquia Drupal recommended project.
NA
- Follow readme and user should be able to install ACMS application.

ACMS-1726: update readme to include ACMS installation steps.

---

.github/workflows/orca.yml

This reverts commit d8b1d621849e3e2e2511a2d5498de52a3f0caeb5.
**Motivation**
Added back scheduled ORCA jobs.
Reverted back previous commit.
N/A
N/A

ACMS-1841: Added back scheduled ORCA jobs

---

.github/workflows/orca.yml

**Motivation**
This adds Google API related credentials to enable Domo Integration.

ORCA-557: Enable Domo

---

.github/workflows/orca.yml

**Motivation**
Fixes #[ACMS-3593](https://acquia.atlassian.net/browse/ACMS-3593)
Update node to latest version v20 and actions to v4.
NA
Verify CI.

ACMS-3593: Update node to latest version v20 and actions to v4.

---

.github/dependabot.yml
.github/release-drafter-2.x.yml

ACMS-4124: Updated the dependabot and release drafter configurations.

---

README.md

**Motivation**
Made minor fixes in README file.
The README file updated.
N/A.
N/A.

ACMS-000: Minor fixes in README file.

---

.github/workflows/orca.yml

- Let's only test D9 in this version of DRP

POST D11 release pipeline changes : 1.x

---

.github/workflows/orca.yml

- Our main objective is to test D10 through this branch.

POST D11 release pipeline changes: 2.x

---

README.md
composer.json
composer.lock

**Motivation**
ACMS-4134
ACMS-4323

Updated README file

---

composer.json
composer.lock

Fixes error: https://github.com/acquia/drupal-recommended-project/issues/815#issuecomment-3009215182.

Removed dealerdirect/phpcodesniffer-composer-installer dependency as it's fixed now.
